# Generated by Django 5.0.6 on 2024-07-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity1',
            new_name='quantity',
        ),
    ]
